-- =========================================
-- EMPLOYEE
-- =========================================
CREATE TABLE IF NOT EXISTS employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    department VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL,
    joining_date DATE NOT NULL
);

-- =========================================
-- REVIEW CYCLE
-- =========================================
CREATE TABLE IF NOT EXISTS review_cycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    CONSTRAINT chk_dates CHECK (end_date >= start_date)
);

-- =========================================
-- PERFORMANCE REVIEW
-- =========================================
CREATE TABLE IF NOT EXISTS performance_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    review_cycle_id BIGINT NOT NULL,
    rating INT NOT NULL,
    reviewer_notes CLOB,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pr_employee
        FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE,

    CONSTRAINT fk_pr_cycle
        FOREIGN KEY (review_cycle_id) REFERENCES review_cycle(id) ON DELETE CASCADE,

    CONSTRAINT chk_rating CHECK (rating BETWEEN 1 AND 5),

    CONSTRAINT uk_emp_cycle UNIQUE (employee_id, review_cycle_id)
);

-- Indexes (use IF NOT EXISTS as well)
CREATE INDEX IF NOT EXISTS idx_pr_cycle
    ON performance_review(review_cycle_id);

CREATE INDEX IF NOT EXISTS idx_pr_emp_cycle
    ON performance_review(employee_id, review_cycle_id);

-- =========================================
-- GOALS
-- =========================================
CREATE TABLE IF NOT EXISTS goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    review_cycle_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_goals_employee
        FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE,

    CONSTRAINT fk_goals_cycle
        FOREIGN KEY (review_cycle_id) REFERENCES review_cycle(id) ON DELETE CASCADE,

    CONSTRAINT chk_status CHECK (status IN ('pending','completed','missed'))
);

CREATE INDEX IF NOT EXISTS idx_goals_emp_cycle
    ON goals(employee_id, review_cycle_id);
-- =========================================
-- EMPLOYEE
-- =========================================
INSERT INTO employee (name, department, role, joining_date)
VALUES
('Alice Johnson', 'Engineering', 'Software Engineer', DATE '2022-01-15'),
('Bob Smith', 'Engineering', 'Senior Developer', DATE '2021-06-10'),
('Charlie Brown', 'HR', 'HR Manager', DATE '2020-03-20'),
('Diana Prince', 'Finance', 'Financial Analyst', DATE '2023-02-01');

-- =========================================
-- REVIEW CYCLE
-- =========================================
INSERT INTO review_cycle (name, start_date, end_date)
VALUES
('Q1 2026', DATE '2026-01-01', DATE '2026-03-31'),
('Q2 2026', DATE '2026-04-01', DATE '2026-06-30');

-- =========================================
-- PERFORMANCE REVIEW
-- =========================================
INSERT INTO performance_review
(employee_id, review_cycle_id, rating, reviewer_notes)
VALUES
(1, 1, 5, 'Outstanding delivery and ownership'),
(2, 1, 4, 'Strong performance with good collaboration'),
(3, 1, 4, 'Improved hiring turnaround significantly'),
(4, 1, 3, 'Met expectations with room for improvement');

-- =========================================
-- GOALS
-- =========================================
INSERT INTO goals
(employee_id, review_cycle_id, title, status)
VALUES
(1, 1, 'Complete microservice migration', 'completed'),
(1, 1, 'Improve API latency by 20%', 'pending'),

(2, 1, 'Lead release automation initiative', 'completed'),

(3, 1, 'Reduce hiring SLA by 15%', 'completed'),

(4, 1, 'Prepare quarterly budget report', 'missed'),

(1, 2, 'Implement performance dashboard', 'pending'),
(2, 2, 'Mentor 2 junior developers', 'pending');
